class DomainError(Exception): ...


class InvalidEmailError(DomainError): ...


class InvalidPasswordError(DomainError): ...


class CodeExpiredError(DomainError): ...


class InvalidCodeError(DomainError): ...
