class DomainError(Exception): ...


class UserError(DomainError): ...


class InvalidEmailError(UserError): ...


class InvalidPasswordError(UserError): ...


class InvalidTimestampError(UserError): ...
