class DomainError(Exception): ...


class InvalidTimestampError(DomainError): ...


class RequiredFieldError(DomainError): ...


class InvalidEmailError(DomainError): ...


class InvalidPasswordError(DomainError): ...


class CodeTypeError(DomainError): ...


class CodeStatusError(DomainError): ...
