from datetime import datetime
from typing import Protocol

from application.dto.user_dto import UserPersistenceDTO
from application.dto.verification_code_dto import (
    VerificationCodePersistenceDTO,
)
from application.events.integration_events import IntegrationEvent


class UserRepositoryPort(Protocol):
    """Defines persistence operations for User entities."""

    async def create(self, user_record: UserPersistenceDTO): ...
    async def update(self, user_record: UserPersistenceDTO): ...
    async def delete(self, public_id: str): ...
    async def get_by_email(self, email: str) -> UserPersistenceDTO | None: ...
    async def get_by_public_id(
        self, public_id: str
    ) -> UserPersistenceDTO | None: ...
    async def exists_by_email(self, email: str) -> bool: ...
    async def exists_by_public_id(self, public_id: str) -> bool: ...
    async def is_active(self, public_id: str) -> bool: ...


class VerificationCodeRepositoryPort(Protocol):
    """Defines persistence operations for verification codes."""

    async def create(self, code_record: VerificationCodePersistenceDTO): ...
    async def update(self, code_record: VerificationCodePersistenceDTO): ...
    async def get_by_user_id_and_code(
        self, user_public_id: str, code: str
    ) -> VerificationCodePersistenceDTO | None: ...
    async def delete_all(self, public_id: str): ...


class TokenRepositoryPort(Protocol):
    """Defines persistence operations for tokens."""

    async def save_refresh(self, sub: str, jti: str, expires_at: datetime): ...
    async def revoke_all_refreshes(self, sub: str): ...
    async def exists(self, jti: str) -> bool: ...
    async def is_revoke(self, jti: str) -> bool: ...


class UnitOfWorkPort(Protocol):
    """Defines transactional boundaries for application operations."""

    async def __enter__(self) -> 'UnitOfWorkPort': ...
    async def __exit__(self, exc_type, exc_value, traceback): ...


class HasherPort(Protocol):
    """Defines password hashing and verification operations."""

    def hash(self, raw_password: str) -> str: ...
    def verify_password(
        self, plain_password: str, hashed_password: str
    ) -> bool: ...


class MessagePublisherPort(Protocol):
    """Defines integration event publishing operations."""

    async def publish(self, integration_event: IntegrationEvent) -> None: ...


class TokenManagerPort(Protocol):
    """Defines token generation and validation operations."""

    def new_pair_token(self, sub: str) -> tuple[dict, dict]: ...
    def new_access(self, sub: str) -> str: ...
    def validate(self, token: str) -> dict: ...
