import uuid
from dataclasses import dataclass, field
from enum import StrEnum, auto

from application.events.email_payload import EmailPayload


class IntegrationEventType(StrEnum):
    """Represents an integration event types."""

    SEND_EMAIL_VERIFICATION_CODE = auto()
    SEND_NOTIFICATION_EMAIL_VERIFIED = auto()

    SEND_PASSWORD_RESET_CODE = auto()
    SEND_NOTIFICATION_PASSWORD_RESET = auto()

    SEND_PASSWORD_CHANGE_CODE = auto()
    SEND_NOTIFICATION_PASSWORD_CHANGED = auto()

    SEND_EMAIL_CHANGE_CODE = auto()
    SEND_NOTIFICATION_EMAIL_CHANGED = auto()

    SEND_DELETE_CODE = auto()
    SEND_NOTIFICATION_DELETED = auto()


@dataclass(slots=True)
class IntegrationEvent:
    """
    Represents an integration message (intent) to be published.

    Attributes:
        type (IntegrationEventType): The specific type of the event.
        data (EmailPayload): The DTO following the EmailPayload protocol.
        id (uuid.UUID): Unique identifier for the event (autogenerated).
    """

    type: IntegrationEventType
    data: EmailPayload
    id: uuid.UUID = field(default_factory=uuid.uuid4)

    @property
    def payload(self) -> dict:
        """
        Returns the processed dictionary from the data object.
        This property calls the to_dict() method of the EmailPayload,
        ensuring fields like 'expiration' and 'deadline' are formatted.
        """
        return self.data.to_dict()
